name: "hello Actions"
description: "Greet someone"
author: "Adam"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: Dockerfile

branding:
  icon: "cloud-snow"
  color: "yellow"